### ISSUE TITLE
Recurring duplicate text channel update messages

### ISSUE THREAD

**Issue by nasisakk** [caf203/loggerv3#26]
Repro Steps (Inconsistent):

- Admin modifies a channel permission
- Logger emits a message to the specified channels saying "Texture channel was updated (ChanName)\n Creation...etc...role RoleName"
- Logger re-emits a message every 10 minutes indefinitely.  Sometimes it will eventually stop it self, sometimes I have to spend a couple hours trying various things on the server until Logger stops.  I have been unable to narrow down the actual cause/fix for this yet.

![image](https://user-images.githubusercontent.com/18223108/140759415-b5be6982-d254-4c2a-a2e6-2a2cdde50585.png)

**Comment by curtisf** [comment]
If you can invite it to another server and can't reproduce this issue (I can't), do you have any other bots on your server? I notice the bot, in the screenshots, is posting empty channel updates on a fixed schedule. Logger itself doesn't utilize anything like that to repeat a log or any timer of 10 minutes whatsoever. I also notice that there are no properties being listed as changed in the subsequent embeds, which makes me think this issue is a bot updating a channel property Logger doesn't support.

**Comment by nasisakk** [comment]
There is another bot that **does** assign per-channel-per-user permissions upon request ("!join this-channel"), however, all operations of that bot shows up in the audit log (and nothing is present there).  I'll dig deeper, however.

**Comment by nasisakk** [comment]
I'm going to close this out, since it's not on you.

The other bot _**was**_ assigning permissions to the channel in question every 10 minutes, however, it was the same permissions repeatedly (have since fixed). This wouldn't trigger an entry in the audit log and no permissions actually changed--however I did confirm after spinning up _another_ bot that it was receiving the channel changed events without really any reasonable data.  So I'll chalk this one up to discord being discord.
